Add pause and unpause functions to OverlayV1Factory and OverlayV1Market
overlay-market/v1-core pull request #122
Opened 2024-01-02 19:52 UTC by magnetto90

2024-01-02 23:44 UTC, EperezOk commented on contracts/OverlayV1Market.sol
> +    function update() public whenNotPaused returns (Oracle.Data memory) {
I think putting the `whenNotPaused` modifier here would be enough to pause the `build`, `unwind` and `liquidate` as well, since those methods call this one.

2024-01-03 13:44 UTC, TomasCImach requested changes

2024-01-03 13:44 UTC, TomasCImach commented on contracts/OverlayV1Factory.sol
We don't want the modifier `onlyGuardian` on the pause functions, as the PAUSER role should have a lower permission level than the GUARDIAN (that can permanently shut down the market).

2024-01-03 19:00 UTC, magnetto90 commented on contracts/OverlayV1Factory.sol
Ok!

2024-01-04 00:02 UTC, magnetto90 commented on contracts/OverlayV1Market.sol
> +    function update() public whenNotPaused returns (Oracle.Data memory) {
Done!

2024-01-04 02:07 UTC, EperezOk submitted a review, later dismissed

2024-01-12 15:15 UTC, TomasCImach approved these changes

2024-01-12 15:16 UTC, merged