Renamos Token from OVL to OV
overlay-market/v1-core pull request #140
Opened 2024-01-12 21:24 UTC by magnetto90

Update token symbol and variable names

2024-01-13 12:53 UTC, TomasCImach requested changes
Renaming looks good. Migrate Refactor of AccessControl to other PR.

2024-01-13 12:53 UTC, TomasCImach commented on contracts/OverlayV1Token.sol
> +import "@openzeppelin/contracts/access/AccessControl.sol";
Propose this change in a different PR.

2024-01-13 12:53 UTC, TomasCImach commented on tests/OverlayV1Token.t.sol
Migrate to Refactor PR

2024-01-13 13:06 UTC, magnetto90 commented on tests/OverlayV1Token.t.sol
Done in #141 but this one has to be merge before.

2024-01-15 18:06 UTC, TomasCImach approved these changes
Looks good! Tests are passing

2024-01-15 18:45 UTC, EperezOk approved these changes

2024-01-15 20:10 UTC, merged