S/add oi oishares to events
overlay-market/v1-core pull request #191
Opened 2024-03-20 14:34 UTC by magnetto90

2024-03-20 17:30 UTC, EperezOk requested changes

2024-03-20 17:30 UTC, EperezOk commented on contracts/OverlayV1Market.sol
> +        }
I would replace these 5 lines with:
```js
emit Build(msg.sender, positionId_, oi, debt, isLong, price, oiLong, isLong ? oiLongShares : oiShortShares);
```
I think it should work.

2024-03-20 17:30 UTC, EperezOk commented on contracts/OverlayV1Market.sol
> +        if (pos.isLong) {
Same recommendation as in the `Build` event.

2024-03-20 17:30 UTC, EperezOk commented on contracts/OverlayV1Market.sol
> +        }
Same recommendation as in the build event.

2024-03-20 18:38 UTC, EperezOk commented on contracts/OverlayV1Market.sol
> +        }
You are right about replacing `oiLong` as well.

Regarding what is better, I think what I suggested improves readability, and having one extra comparison is negligible.

2024-03-21 15:42 UTC, EperezOk requested changes
Last changes request, promise!

2024-03-21 15:42 UTC, EperezOk commented on contracts/OverlayV1Market.sol
> +        bool isLong = pos.isLong;
No need to create a separate `isLong` variable, we can use `pos.isLong` directly (it's already loaded in memory).

2024-03-21 15:42 UTC, EperezOk commented on contracts/OverlayV1Market.sol
> +        bool isLong = pos.isLong;
No need to create a separate `isLong` variable, we can use `pos.isLong` directly (it's already loaded in memory).

2024-03-21 16:05 UTC, magnetto90 commented on contracts/OverlayV1Market.sol
> +        bool isLong = pos.isLong;
As always, you are right!

2024-03-21 16:09 UTC, EperezOk approved these changes

2024-03-25 17:41 UTC, EperezOk approved these changes

2024-03-25 18:17 UTC, merged